name: Build and Test .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuração do .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src

    # Build do projeto
    - name: Build
      run: dotnet build src --configuration Release --no-restore

    # Executar testes
    - name: Run Tests
      run: dotnet test src --no-build --verbosity normal
