name: ZapZap

on:
  push:
    branches:
      - main
jobs:
  zap_scan:
    runs-on: self-hosted
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Java (se necessário)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          version: '11'

      - name: Run ZAP Scan
        run: |
          # Baixar e rodar o ZAP no Windows
          curl -L https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_windows.zip -o zap.zip
          Expand-Archive zap.zip -DestinationPath C:\ZAP
          Start-Process -FilePath "C:\ZAP\zap.exe" -ArgumentList "-daemon -host 127.0.0.1 -port 8080" -NoNewWindow
          # Espera um tempo para o ZAP iniciar
          Start-Sleep -Seconds 10
          # Agora, executa o scan com o ZAP
          curl -X GET "http://127.0.0.1:8080/JSON/ascan/action/scan/?url=https://www.zaproxy.org&apikey=your_api_key"
